"""Remove genres attribute

Revision ID: ec8f62d82423
Revises: af50fb75604e
Create Date: 2024-02-18 20:29:23.255660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec8f62d82423'
down_revision = 'af50fb75604e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('genre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.VARCHAR(length=128), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
